document.writeln("<div class=\'navbar-wrapper\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <nav class=\'navbar navbar-inverse navbar-fixed-top\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("          <div class=\'navbar-header\'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#navbar\' aria-expanded=\'false\' aria-controls=\'navbar\'>");
document.writeln("              <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("              <span class=\'icon-bar\'></span>");
document.writeln("              <span class=\'icon-bar\'></span>");
document.writeln("              <span class=\'icon-bar\'></span>");
document.writeln("            </button>");
document.writeln("            <a class=\'navbar-brand\' href=\'../index.html\'>明月橙的个人主页</a>");
document.writeln("          </div>");
document.writeln("          <div id=\'navbar\' class=\'navbar-collapse collapse\'>");
document.writeln("            <ul class=\'nav navbar-nav\'>");
document.writeln("              <li ><a href=\'../index.html\'>主页</a></li>");
document.writeln("              <!-- 项目 -->");
document.writeln("              <li class=\'dropdown\' >");
document.writeln("                <a href=\'#\'class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>完整项目 <span class=\'caret\'></span></a>");
document.writeln("                <ul class=\'dropdown-menu\'>");
document.writeln("                  <li class=\'dropdown-header\'>项目名称</li>");
document.writeln("                  <li><a href=\'#\'>独立游戏《Axis》</a></li>");
document.writeln("                </ul>");
document.writeln("              </li>");
document.writeln("              <li><a href=\'#\'>小型demo</a></li>");
document.writeln("              <li><a href=\'#\'>技术文章</a></li>");
document.writeln("              <!-- drop down -->");
document.writeln("              <li class=\'dropdown\'>");
document.writeln("                <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>Dropdown <span class=\'caret\'></span></a>");
document.writeln("                <ul class=\'dropdown-menu\'>");
document.writeln("                  <li><a href=\'#\'>Action</a></li>");
document.writeln("                  <li><a href=\'#\'>Another action</a></li>");
document.writeln("                  <li><a href=\'#\'>Something else here</a></li>");
document.writeln("                  <li role=\'separator\' class=\'divider\'></li>");
document.writeln("                  <li class=\'dropdown-header\'>Nav header</li>");
document.writeln("                  <li><a href=\'#\'>Separated link</a></li>");
document.writeln("                  <li><a href=\'#\'>One more separated link</a></li>");
document.writeln("                </ul>");
document.writeln("              </li>");
document.writeln("");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </nav>");
document.writeln("    </div>");
document.writeln("</div>");