document.writeln("<div class=\"navbar-wrapper\">");
document.writeln("    <div class=\"container\">");
document.writeln("      <nav class=\"navbar navbar-inverse navbar-fixed-top\">");
document.writeln("        <div class=\"container\">");
document.writeln("          <div class=\"navbar-header\">");
document.writeln("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">");
document.writeln("              <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("              <span class=\"icon-bar\"></span>");
document.writeln("              <span class=\"icon-bar\"></span>");
document.writeln("              <span class=\"icon-bar\"></span>");
document.writeln("            </button>");
document.writeln("            <a class=\"navbar-brand\" href=\"../index.html\">明月橙的个人作品</a>");
document.writeln("          </div>");
document.writeln("          <div id=\"navbar\" class=\"navbar-collapse collapse\">");
document.writeln("            <ul class=\"nav navbar-nav\">");
document.writeln("              <li ><a href=\"#\" onClick=\"javascript :history.back(-1);\">返回上一页</a></li>");
document.writeln("              <li><a href=\"javascript:scroll(0,0)\">返回顶部</a></li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </nav>");
document.writeln("    </div>");
document.writeln("</div>");